/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appHomeRouteRouteImport } from './routes/(app)/_home/route'
import { Route as appAuthRouteRouteImport } from './routes/(app)/_auth/route'
import { Route as appAppRouteRouteImport } from './routes/(app)/_app/route'
import { Route as appAdminRouteRouteImport } from './routes/(app)/_admin/route'
import { Route as appHomeIndexRouteImport } from './routes/(app)/_home/index'
import { Route as appHomeUpgradeRouteImport } from './routes/(app)/_home/upgrade'
import { Route as appHomeContactRouteImport } from './routes/(app)/_home/contact'
import { Route as appAuthLoginRouteImport } from './routes/(app)/_auth/login'
import { Route as appAppAccountRouteRouteImport } from './routes/(app)/_app/account/route'
import { Route as appHomeTemplatesIndexRouteImport } from './routes/(app)/_home/templates/index'
import { Route as appHomeShowcaseIndexRouteImport } from './routes/(app)/_home/showcase/index'
import { Route as appHomeBadgeIndexRouteImport } from './routes/(app)/_home/badge/index'
import { Route as appHomeActivateIndexRouteImport } from './routes/(app)/_home/activate/index'
import { Route as appAppOverviewIndexRouteImport } from './routes/(app)/_app/overview/index'
import { Route as appAppChatIndexRouteImport } from './routes/(app)/_app/chat/index'
import { Route as appHomeLegalsTermsRouteImport } from './routes/(app)/_home/legals/terms'
import { Route as appHomeLegalsPrivacyPolicyRouteImport } from './routes/(app)/_home/legals/privacy-policy'
import { Route as appHomeShowcaseSubmitIndexRouteImport } from './routes/(app)/_home/showcase/submit/index'
import { Route as appAppAccountSecurityIndexRouteImport } from './routes/(app)/_app/account/security/index'
import { Route as appAppAccountProfileIndexRouteImport } from './routes/(app)/_app/account/profile/index'
import { Route as appAppAccountBillingIndexRouteImport } from './routes/(app)/_app/account/billing/index'
import { Route as appAppAccountApiKeyIndexRouteImport } from './routes/(app)/_app/account/api-key/index'
import { Route as appAdminSUsersIndexRouteImport } from './routes/(app)/_admin/s/users/index'
import { Route as appAdminSShowcaseIndexRouteImport } from './routes/(app)/_admin/s/showcase/index'
import { Route as appAdminSOverviewIndexRouteImport } from './routes/(app)/_admin/s/overview/index'
import { Route as appAdminSEventsIndexRouteImport } from './routes/(app)/_admin/s/events/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appHomeRouteRoute = appHomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => appRouteRoute,
} as any)
const appAuthRouteRoute = appAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => appRouteRoute,
} as any)
const appAppRouteRoute = appAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminRouteRoute = appAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => appRouteRoute,
} as any)
const appHomeIndexRoute = appHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appHomeUpgradeRoute = appHomeUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appHomeContactRoute = appHomeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appAuthLoginRoute = appAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => appAuthRouteRoute,
} as any)
const appAppAccountRouteRoute = appAppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appHomeTemplatesIndexRoute = appHomeTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appHomeShowcaseIndexRoute = appHomeShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appHomeBadgeIndexRoute = appHomeBadgeIndexRouteImport.update({
  id: '/badge/',
  path: '/badge/',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appHomeActivateIndexRoute = appHomeActivateIndexRouteImport.update({
  id: '/activate/',
  path: '/activate/',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appAppOverviewIndexRoute = appAppOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppChatIndexRoute = appAppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appHomeLegalsTermsRoute = appHomeLegalsTermsRouteImport.update({
  id: '/legals/terms',
  path: '/legals/terms',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appHomeLegalsPrivacyPolicyRoute =
  appHomeLegalsPrivacyPolicyRouteImport.update({
    id: '/legals/privacy-policy',
    path: '/legals/privacy-policy',
    getParentRoute: () => appHomeRouteRoute,
  } as any)
const appHomeShowcaseSubmitIndexRoute =
  appHomeShowcaseSubmitIndexRouteImport.update({
    id: '/showcase/submit/',
    path: '/showcase/submit/',
    getParentRoute: () => appHomeRouteRoute,
  } as any)
const appAppAccountSecurityIndexRoute =
  appAppAccountSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => appAppAccountRouteRoute,
  } as any)
const appAppAccountProfileIndexRoute =
  appAppAccountProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => appAppAccountRouteRoute,
  } as any)
const appAppAccountBillingIndexRoute =
  appAppAccountBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => appAppAccountRouteRoute,
  } as any)
const appAppAccountApiKeyIndexRoute =
  appAppAccountApiKeyIndexRouteImport.update({
    id: '/api-key/',
    path: '/api-key/',
    getParentRoute: () => appAppAccountRouteRoute,
  } as any)
const appAdminSUsersIndexRoute = appAdminSUsersIndexRouteImport.update({
  id: '/s/users/',
  path: '/s/users/',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appAdminSShowcaseIndexRoute = appAdminSShowcaseIndexRouteImport.update({
  id: '/s/showcase/',
  path: '/s/showcase/',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appAdminSOverviewIndexRoute = appAdminSOverviewIndexRouteImport.update({
  id: '/s/overview/',
  path: '/s/overview/',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appAdminSEventsIndexRoute = appAdminSEventsIndexRouteImport.update({
  id: '/s/events/',
  path: '/s/events/',
  getParentRoute: () => appAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/account': typeof appAppAccountRouteRouteWithChildren
  '/login': typeof appAuthLoginRoute
  '/contact': typeof appHomeContactRoute
  '/upgrade': typeof appHomeUpgradeRoute
  '/': typeof appHomeIndexRoute
  '/legals/privacy-policy': typeof appHomeLegalsPrivacyPolicyRoute
  '/legals/terms': typeof appHomeLegalsTermsRoute
  '/chat/': typeof appAppChatIndexRoute
  '/overview/': typeof appAppOverviewIndexRoute
  '/activate/': typeof appHomeActivateIndexRoute
  '/badge/': typeof appHomeBadgeIndexRoute
  '/showcase/': typeof appHomeShowcaseIndexRoute
  '/templates/': typeof appHomeTemplatesIndexRoute
  '/s/events/': typeof appAdminSEventsIndexRoute
  '/s/overview/': typeof appAdminSOverviewIndexRoute
  '/s/showcase/': typeof appAdminSShowcaseIndexRoute
  '/s/users/': typeof appAdminSUsersIndexRoute
  '/account/api-key/': typeof appAppAccountApiKeyIndexRoute
  '/account/billing/': typeof appAppAccountBillingIndexRoute
  '/account/profile/': typeof appAppAccountProfileIndexRoute
  '/account/security/': typeof appAppAccountSecurityIndexRoute
  '/showcase/submit/': typeof appHomeShowcaseSubmitIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof appAppAccountRouteRouteWithChildren
  '/login': typeof appAuthLoginRoute
  '/contact': typeof appHomeContactRoute
  '/upgrade': typeof appHomeUpgradeRoute
  '/': typeof appHomeIndexRoute
  '/legals/privacy-policy': typeof appHomeLegalsPrivacyPolicyRoute
  '/legals/terms': typeof appHomeLegalsTermsRoute
  '/chat': typeof appAppChatIndexRoute
  '/overview': typeof appAppOverviewIndexRoute
  '/activate': typeof appHomeActivateIndexRoute
  '/badge': typeof appHomeBadgeIndexRoute
  '/showcase': typeof appHomeShowcaseIndexRoute
  '/templates': typeof appHomeTemplatesIndexRoute
  '/s/events': typeof appAdminSEventsIndexRoute
  '/s/overview': typeof appAdminSOverviewIndexRoute
  '/s/showcase': typeof appAdminSShowcaseIndexRoute
  '/s/users': typeof appAdminSUsersIndexRoute
  '/account/api-key': typeof appAppAccountApiKeyIndexRoute
  '/account/billing': typeof appAppAccountBillingIndexRoute
  '/account/profile': typeof appAppAccountProfileIndexRoute
  '/account/security': typeof appAppAccountSecurityIndexRoute
  '/showcase/submit': typeof appHomeShowcaseSubmitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/_admin': typeof appAdminRouteRouteWithChildren
  '/(app)/_app': typeof appAppRouteRouteWithChildren
  '/(app)/_auth': typeof appAuthRouteRouteWithChildren
  '/(app)/_home': typeof appHomeRouteRouteWithChildren
  '/(app)/_app/account': typeof appAppAccountRouteRouteWithChildren
  '/(app)/_auth/login': typeof appAuthLoginRoute
  '/(app)/_home/contact': typeof appHomeContactRoute
  '/(app)/_home/upgrade': typeof appHomeUpgradeRoute
  '/(app)/_home/': typeof appHomeIndexRoute
  '/(app)/_home/legals/privacy-policy': typeof appHomeLegalsPrivacyPolicyRoute
  '/(app)/_home/legals/terms': typeof appHomeLegalsTermsRoute
  '/(app)/_app/chat/': typeof appAppChatIndexRoute
  '/(app)/_app/overview/': typeof appAppOverviewIndexRoute
  '/(app)/_home/activate/': typeof appHomeActivateIndexRoute
  '/(app)/_home/badge/': typeof appHomeBadgeIndexRoute
  '/(app)/_home/showcase/': typeof appHomeShowcaseIndexRoute
  '/(app)/_home/templates/': typeof appHomeTemplatesIndexRoute
  '/(app)/_admin/s/events/': typeof appAdminSEventsIndexRoute
  '/(app)/_admin/s/overview/': typeof appAdminSOverviewIndexRoute
  '/(app)/_admin/s/showcase/': typeof appAdminSShowcaseIndexRoute
  '/(app)/_admin/s/users/': typeof appAdminSUsersIndexRoute
  '/(app)/_app/account/api-key/': typeof appAppAccountApiKeyIndexRoute
  '/(app)/_app/account/billing/': typeof appAppAccountBillingIndexRoute
  '/(app)/_app/account/profile/': typeof appAppAccountProfileIndexRoute
  '/(app)/_app/account/security/': typeof appAppAccountSecurityIndexRoute
  '/(app)/_home/showcase/submit/': typeof appHomeShowcaseSubmitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/login'
    | '/contact'
    | '/upgrade'
    | '/'
    | '/legals/privacy-policy'
    | '/legals/terms'
    | '/chat/'
    | '/overview/'
    | '/activate/'
    | '/badge/'
    | '/showcase/'
    | '/templates/'
    | '/s/events/'
    | '/s/overview/'
    | '/s/showcase/'
    | '/s/users/'
    | '/account/api-key/'
    | '/account/billing/'
    | '/account/profile/'
    | '/account/security/'
    | '/showcase/submit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/login'
    | '/contact'
    | '/upgrade'
    | '/'
    | '/legals/privacy-policy'
    | '/legals/terms'
    | '/chat'
    | '/overview'
    | '/activate'
    | '/badge'
    | '/showcase'
    | '/templates'
    | '/s/events'
    | '/s/overview'
    | '/s/showcase'
    | '/s/users'
    | '/account/api-key'
    | '/account/billing'
    | '/account/profile'
    | '/account/security'
    | '/showcase/submit'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/_admin'
    | '/(app)/_app'
    | '/(app)/_auth'
    | '/(app)/_home'
    | '/(app)/_app/account'
    | '/(app)/_auth/login'
    | '/(app)/_home/contact'
    | '/(app)/_home/upgrade'
    | '/(app)/_home/'
    | '/(app)/_home/legals/privacy-policy'
    | '/(app)/_home/legals/terms'
    | '/(app)/_app/chat/'
    | '/(app)/_app/overview/'
    | '/(app)/_home/activate/'
    | '/(app)/_home/badge/'
    | '/(app)/_home/showcase/'
    | '/(app)/_home/templates/'
    | '/(app)/_admin/s/events/'
    | '/(app)/_admin/s/overview/'
    | '/(app)/_admin/s/showcase/'
    | '/(app)/_admin/s/users/'
    | '/(app)/_app/account/api-key/'
    | '/(app)/_app/account/billing/'
    | '/(app)/_app/account/profile/'
    | '/(app)/_app/account/security/'
    | '/(app)/_home/showcase/submit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_home': {
      id: '/(app)/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appHomeRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/_auth': {
      id: '/(app)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/_app': {
      id: '/(app)/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/_admin': {
      id: '/(app)/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAdminRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/_home/': {
      id: '/(app)/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appHomeIndexRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_home/upgrade': {
      id: '/(app)/_home/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof appHomeUpgradeRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_home/contact': {
      id: '/(app)/_home/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof appHomeContactRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_auth/login': {
      id: '/(app)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof appAuthLoginRouteImport
      parentRoute: typeof appAuthRouteRoute
    }
    '/(app)/_app/account': {
      id: '/(app)/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof appAppAccountRouteRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_home/templates/': {
      id: '/(app)/_home/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof appHomeTemplatesIndexRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_home/showcase/': {
      id: '/(app)/_home/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof appHomeShowcaseIndexRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_home/badge/': {
      id: '/(app)/_home/badge/'
      path: '/badge'
      fullPath: '/badge/'
      preLoaderRoute: typeof appHomeBadgeIndexRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_home/activate/': {
      id: '/(app)/_home/activate/'
      path: '/activate'
      fullPath: '/activate/'
      preLoaderRoute: typeof appHomeActivateIndexRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_app/overview/': {
      id: '/(app)/_app/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof appAppOverviewIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/chat/': {
      id: '/(app)/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof appAppChatIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_home/legals/terms': {
      id: '/(app)/_home/legals/terms'
      path: '/legals/terms'
      fullPath: '/legals/terms'
      preLoaderRoute: typeof appHomeLegalsTermsRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_home/legals/privacy-policy': {
      id: '/(app)/_home/legals/privacy-policy'
      path: '/legals/privacy-policy'
      fullPath: '/legals/privacy-policy'
      preLoaderRoute: typeof appHomeLegalsPrivacyPolicyRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_home/showcase/submit/': {
      id: '/(app)/_home/showcase/submit/'
      path: '/showcase/submit'
      fullPath: '/showcase/submit/'
      preLoaderRoute: typeof appHomeShowcaseSubmitIndexRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_app/account/security/': {
      id: '/(app)/_app/account/security/'
      path: '/security'
      fullPath: '/account/security/'
      preLoaderRoute: typeof appAppAccountSecurityIndexRouteImport
      parentRoute: typeof appAppAccountRouteRoute
    }
    '/(app)/_app/account/profile/': {
      id: '/(app)/_app/account/profile/'
      path: '/profile'
      fullPath: '/account/profile/'
      preLoaderRoute: typeof appAppAccountProfileIndexRouteImport
      parentRoute: typeof appAppAccountRouteRoute
    }
    '/(app)/_app/account/billing/': {
      id: '/(app)/_app/account/billing/'
      path: '/billing'
      fullPath: '/account/billing/'
      preLoaderRoute: typeof appAppAccountBillingIndexRouteImport
      parentRoute: typeof appAppAccountRouteRoute
    }
    '/(app)/_app/account/api-key/': {
      id: '/(app)/_app/account/api-key/'
      path: '/api-key'
      fullPath: '/account/api-key/'
      preLoaderRoute: typeof appAppAccountApiKeyIndexRouteImport
      parentRoute: typeof appAppAccountRouteRoute
    }
    '/(app)/_admin/s/users/': {
      id: '/(app)/_admin/s/users/'
      path: '/s/users'
      fullPath: '/s/users/'
      preLoaderRoute: typeof appAdminSUsersIndexRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/_admin/s/showcase/': {
      id: '/(app)/_admin/s/showcase/'
      path: '/s/showcase'
      fullPath: '/s/showcase/'
      preLoaderRoute: typeof appAdminSShowcaseIndexRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/_admin/s/overview/': {
      id: '/(app)/_admin/s/overview/'
      path: '/s/overview'
      fullPath: '/s/overview/'
      preLoaderRoute: typeof appAdminSOverviewIndexRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/_admin/s/events/': {
      id: '/(app)/_admin/s/events/'
      path: '/s/events'
      fullPath: '/s/events/'
      preLoaderRoute: typeof appAdminSEventsIndexRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
  }
}

interface appAdminRouteRouteChildren {
  appAdminSEventsIndexRoute: typeof appAdminSEventsIndexRoute
  appAdminSOverviewIndexRoute: typeof appAdminSOverviewIndexRoute
  appAdminSShowcaseIndexRoute: typeof appAdminSShowcaseIndexRoute
  appAdminSUsersIndexRoute: typeof appAdminSUsersIndexRoute
}

const appAdminRouteRouteChildren: appAdminRouteRouteChildren = {
  appAdminSEventsIndexRoute: appAdminSEventsIndexRoute,
  appAdminSOverviewIndexRoute: appAdminSOverviewIndexRoute,
  appAdminSShowcaseIndexRoute: appAdminSShowcaseIndexRoute,
  appAdminSUsersIndexRoute: appAdminSUsersIndexRoute,
}

const appAdminRouteRouteWithChildren = appAdminRouteRoute._addFileChildren(
  appAdminRouteRouteChildren,
)

interface appAppAccountRouteRouteChildren {
  appAppAccountApiKeyIndexRoute: typeof appAppAccountApiKeyIndexRoute
  appAppAccountBillingIndexRoute: typeof appAppAccountBillingIndexRoute
  appAppAccountProfileIndexRoute: typeof appAppAccountProfileIndexRoute
  appAppAccountSecurityIndexRoute: typeof appAppAccountSecurityIndexRoute
}

const appAppAccountRouteRouteChildren: appAppAccountRouteRouteChildren = {
  appAppAccountApiKeyIndexRoute: appAppAccountApiKeyIndexRoute,
  appAppAccountBillingIndexRoute: appAppAccountBillingIndexRoute,
  appAppAccountProfileIndexRoute: appAppAccountProfileIndexRoute,
  appAppAccountSecurityIndexRoute: appAppAccountSecurityIndexRoute,
}

const appAppAccountRouteRouteWithChildren =
  appAppAccountRouteRoute._addFileChildren(appAppAccountRouteRouteChildren)

interface appAppRouteRouteChildren {
  appAppAccountRouteRoute: typeof appAppAccountRouteRouteWithChildren
  appAppChatIndexRoute: typeof appAppChatIndexRoute
  appAppOverviewIndexRoute: typeof appAppOverviewIndexRoute
}

const appAppRouteRouteChildren: appAppRouteRouteChildren = {
  appAppAccountRouteRoute: appAppAccountRouteRouteWithChildren,
  appAppChatIndexRoute: appAppChatIndexRoute,
  appAppOverviewIndexRoute: appAppOverviewIndexRoute,
}

const appAppRouteRouteWithChildren = appAppRouteRoute._addFileChildren(
  appAppRouteRouteChildren,
)

interface appAuthRouteRouteChildren {
  appAuthLoginRoute: typeof appAuthLoginRoute
}

const appAuthRouteRouteChildren: appAuthRouteRouteChildren = {
  appAuthLoginRoute: appAuthLoginRoute,
}

const appAuthRouteRouteWithChildren = appAuthRouteRoute._addFileChildren(
  appAuthRouteRouteChildren,
)

interface appHomeRouteRouteChildren {
  appHomeContactRoute: typeof appHomeContactRoute
  appHomeUpgradeRoute: typeof appHomeUpgradeRoute
  appHomeIndexRoute: typeof appHomeIndexRoute
  appHomeLegalsPrivacyPolicyRoute: typeof appHomeLegalsPrivacyPolicyRoute
  appHomeLegalsTermsRoute: typeof appHomeLegalsTermsRoute
  appHomeActivateIndexRoute: typeof appHomeActivateIndexRoute
  appHomeBadgeIndexRoute: typeof appHomeBadgeIndexRoute
  appHomeShowcaseIndexRoute: typeof appHomeShowcaseIndexRoute
  appHomeTemplatesIndexRoute: typeof appHomeTemplatesIndexRoute
  appHomeShowcaseSubmitIndexRoute: typeof appHomeShowcaseSubmitIndexRoute
}

const appHomeRouteRouteChildren: appHomeRouteRouteChildren = {
  appHomeContactRoute: appHomeContactRoute,
  appHomeUpgradeRoute: appHomeUpgradeRoute,
  appHomeIndexRoute: appHomeIndexRoute,
  appHomeLegalsPrivacyPolicyRoute: appHomeLegalsPrivacyPolicyRoute,
  appHomeLegalsTermsRoute: appHomeLegalsTermsRoute,
  appHomeActivateIndexRoute: appHomeActivateIndexRoute,
  appHomeBadgeIndexRoute: appHomeBadgeIndexRoute,
  appHomeShowcaseIndexRoute: appHomeShowcaseIndexRoute,
  appHomeTemplatesIndexRoute: appHomeTemplatesIndexRoute,
  appHomeShowcaseSubmitIndexRoute: appHomeShowcaseSubmitIndexRoute,
}

const appHomeRouteRouteWithChildren = appHomeRouteRoute._addFileChildren(
  appHomeRouteRouteChildren,
)

interface appRouteRouteChildren {
  appAdminRouteRoute: typeof appAdminRouteRouteWithChildren
  appAppRouteRoute: typeof appAppRouteRouteWithChildren
  appAuthRouteRoute: typeof appAuthRouteRouteWithChildren
  appHomeRouteRoute: typeof appHomeRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAdminRouteRoute: appAdminRouteRouteWithChildren,
  appAppRouteRoute: appAppRouteRouteWithChildren,
  appAuthRouteRoute: appAuthRouteRouteWithChildren,
  appHomeRouteRoute: appHomeRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
