/**
 * Centralized SEO metadata helpers.
 *
 * `seo()` produces the `meta` + `links` arrays consumed by a TanStack Router
 * route `head()`. Per-route values override the root defaults because
 * `<HeadContent />` dedupes by `name` / `property`, keeping the most specific
 * (deepest) match.
 *
 * Dynamic Open Graph images are generated by the `/og` route handler
 * (Takumi v2). Build the image URL with `ogImageUrl()`.
 */

export const SITE_URL = "https://tanship.dev";
export const SITE_NAME = "Tanship";
export const TWITTER_HANDLE = "@tanship";

export const DEFAULT_TITLE =
	"Tanship — Edge-native SaaS boilerplate for TanStack Start & Cloudflare";
export const DEFAULT_DESCRIPTION =
	"Tanship is a production-ready SaaS boilerplate built on TanStack Start, Cloudflare Workers, Hono, Drizzle, and Better Auth. Ship an edge-native SaaS in days, not months.";
export const DEFAULT_KEYWORDS = [
	"SaaS boilerplate",
	"TanStack Start",
	"Cloudflare Workers",
	"Hono",
	"Drizzle ORM",
	"Better Auth",
	"edge-native",
	"React starter",
	"TypeScript boilerplate"
];

/**
 * Absolute URL of the dynamically rendered Open Graph image.
 * Served by `apps/web/src/routes/og.tsx` via Takumi v2 `ImageResponse`.
 */
export function ogImageUrl(args?: {
	title?: string;
	description?: string;
	eyebrow?: string;
}): string {
	const params = new URLSearchParams();
	if (args?.title) params.set("title", args.title);
	if (args?.description) params.set("description", args.description);
	if (args?.eyebrow) params.set("eyebrow", args.eyebrow);
	const qs = params.toString();
	return `${SITE_URL}/og${qs ? `?${qs}` : ""}`;
}

export interface SeoArgs {
	/** Page-specific title. Combined with the site name. Omit on the home page. */
	title?: string;
	/** Page description. Falls back to the site default. */
	description?: string;
	/** Path beginning with `/` used for `og:url` and the canonical link. */
	path?: string;
	/** Override the OG/Twitter image. Defaults to a dynamic Takumi image. */
	image?: string;
	/** Eyebrow/label rendered on the dynamic OG image. */
	ogEyebrow?: string;
	keywords?: string[];
	/** Emit `robots: noindex` for private or utility pages. */
	noindex?: boolean;
}

type MetaTag =
	| { title: string }
	| { name: string; content: string }
	| { property: string; content: string };

export function seo(args: SeoArgs = {}): {
	meta: MetaTag[];
	links: { rel: string; href: string }[];
} {
	const title = args.title ? `${args.title} — ${SITE_NAME}` : DEFAULT_TITLE;
	const description = args.description ?? DEFAULT_DESCRIPTION;
	const url = `${SITE_URL}${args.path ?? ""}`;
	const image =
		args.image ??
		ogImageUrl({
			title: args.title ?? SITE_NAME,
			description: args.description,
			eyebrow: args.ogEyebrow
		});
	const keywords = (args.keywords ?? DEFAULT_KEYWORDS).join(", ");

	const meta: MetaTag[] = [
		{ title },
		{ name: "description", content: description },
		{ name: "keywords", content: keywords },
		{
			name: "robots",
			content: args.noindex
				? "noindex, nofollow"
				: "index, follow, max-image-preview:large"
		},

		// Open Graph
		{ property: "og:type", content: "website" },
		{ property: "og:site_name", content: SITE_NAME },
		{ property: "og:title", content: title },
		{ property: "og:description", content: description },
		{ property: "og:url", content: url },
		{ property: "og:image", content: image },
		{ property: "og:image:width", content: "1200" },
		{ property: "og:image:height", content: "630" },
		{ property: "og:image:alt", content: title },

		// Twitter
		{ name: "twitter:card", content: "summary_large_image" },
		{ name: "twitter:title", content: title },
		{ name: "twitter:description", content: description },
		{ name: "twitter:image", content: image },
		{ name: "twitter:site", content: TWITTER_HANDLE },
		{ name: "twitter:creator", content: TWITTER_HANDLE }
	];

	return {
		meta,
		links: [{ rel: "canonical", href: url }]
	};
}
